site_name: "Termynal"
site_url: "https://pypi.org/project/termynal"
site_description: "A lightweight and modern animated terminal window for mkdocs"

repo_name: "daxartio/termynal"
repo_url: "https://github.com/daxartio/termynal"
edit_uri: "edit/main/docs/"

copyright: "Copyright &copy; 2023 Danil Akhtarov"

nav:
  - "Home": README.md
  - "Configuration": configuration.md
  - "Contributing": contributing.md
  - "Changelog": changelog.md
  - "Code of Conduct": code-of-conduct.md

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: yellow

plugins:
  - termynal
  - search:
      lang: en

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - termynal:
      promt_in_multiline: false
      prompt_literal_start:
        - "$ "
        - "&gt; "
        - "&gt;&gt;&gt; "
  - markdown_include.include:
      base_path: .
